### PR TITLE
FHAC-895: Revert EventOutComeIndicator field

### PR DESCRIPTION
**Pull request by mhpnguyen**
Revert back EventOutComeIndicator field
@sailajaa @TabassumJafri, @christophermay07  Can you please review it?

### CODE REVIEW

**Comment by TabassumJafri** [comment]
Reviewed changes and good with merge.

**Comment by christophermay07** [comment]
In the future, use "git revert" to undo a commit.

**Comment by christophermay07** [comment]
I've reviewed this PR, endorsing for merge despite comment.

**Comment by sailajaa** [comment]
Merging PR without further comments.

**Pull request merged**
