### PR TITLE
FHAC-729: Updated maven-jaxb2-plugin

### PR DESCRIPTION
**Pull request by christophermay07**
Updated maven-jaxb2-plugin, plus other POM cleanup

### CODE REVIEW

**Comment by vdmehta06** [comment]
Reviewed change and good with merge.

**Comment by christophermay07** [comment]
@vdmehta06 @mhpnguyen forgot to explicitly assign you both for review on this repo

**Comment by mhpnguyen** [comment]
Endorse for merging without any comments

**Comment by vdmehta06** [comment]
Green to merge with PR changes comment response.

**Pull request merged**
